### ISSUE TITLE
not distributing parallel tasks across cores 

### ISSUE THREAD

**Issue by bsu-wrudisill** [taobrienlbl/simplempi#1]
Hello, 

Thanks for the awesome tool. I'm trying to use this on NERSC — I'm getting the following error: 

I'm running the 'parfor_test' script that you have in the examples. I've installed the package via pip. And, I've loaded mpi using 'module load openmpi'....

It looks like the tasks get repeated 4x times rather than getting distributed across 4 processors. 
![image](https://github.com/user-attachments/assets/e77d366c-4d1e-42de-a0c4-5b956abfa28c)

Any ideas on what I could check? Thanks!

**Comment by taobrienlbl** [comment]
Glad this might be useful @bsu-wrudisill !  I've seen errors like that before when the MPI used by python doesn't match what's used in NERSC.  Two suggestions for things to check on:

1. Install mpi4py in your environment following [NERSC's special instructions for mpi4py](https://docs.nersc.gov/development/languages/python/using-python-perlmutter/#mpi4py-on-perlmutter)
2. Use `srun` instead of `mpirun`

I'll be curious if this works out!

**Comment by taobrienlbl** [comment]
also, I've never done `module load openmpi` with simplempi before: I'm not sure whether/how that would work.  You might try the above changes and also not load that module.

**Comment by bsu-wrudisill** [comment]
Awesome! I followed the instructions for installing mpi4py, rebuilt the conda environment, and was able to get this working. 

Thanks a ton. This has sped up my workflow a lot.

**Comment by taobrienlbl** [comment]
Awesome!  Thanks for letting me know; glad that worked!
